### ISSUE TITLE
Support for signals

### ISSUE THREAD

**Issue by dar-clgo** [Angular-Dynamic-Hooks/ngx-dynamic-hooks#45]
Signals in dynamic components seem to work but not exactly?
`someInput = input<string>();`

The above value normally would be accessed via `this.someInput().split(' ')`, however in the case of dynamic components, it seems they're not signals, but instead need to access directly via `this.someInput.split(' ')`.

This leads to problems with typing due to the IDE thinking it should have a signal<string> and not a string.

**Comment by MTobisch** [comment]
Hey there,

thank you for bringing this bug to my attention. I had not yet implemented support for signal-based inputs as they're still in developer preview. Fortunately, it seems I only had to adjust a few lines to make them generally work with the library.

Can you try **version 3.0.4** of the library and report back if the bug still occurs? Thanks!

**Comment by dar-clgo** [comment]
Thanks for the quick update, working now! 👍
